server:
  port: 8088

spring:
  profiles:
    include: dev

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
  jwt:
    secret: ${JWT_SECRET}
