server:
  port: 8088

spring:
  profiles:
    include: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
  jwt:
    secret: ${JWT_SECRET}

  server:
    max-http-header-size: 40000
    tomcat:
      max-http-post-size: 20971520  # POST 요청의 최대 크기를 20MB로 설정
